apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: m-mysql
spec:
  selector:
    matchLabels:
      app: m-mysql
  serviceName: "m-mysql"
  template:
    metadata:
      labels:
        app: m-mysql
    spec:
      containers:
        - name: m-mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: m-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: m-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: m-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: "user_db"
          ports:
            - containerPort: 3306
          volumeMounts:
           - mountPath: /var/lib/mysql
             name: mysql-storage
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: m-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: m-mysql